version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - yum install -y maven
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package

artifacts:
  files:
    - '**/LoginWebApp-1.war'
    - 'appspec.yaml'
  discard-paths: yes
